name: Terraform Plan
description: "Github Action to Run Terraform Plan"

inputs:
  path:
    description: "Path to the Terraform files directory"
    required: true
  label:
    description: "A friendly name for the plan (if specified, needs to match the label used in the apply action)"
    required: false
  backend_config_file:
    description: "Backend config file for terraform"
    required: false
  var_file:
    description: "List of tfvars files to use"
    required: false
  add_github_comment:
    description: |
      The default is "true", which adds a comment to the PR with the results of the plan.
      Set to "changes-only" to add a comment only when the plan indicates there are changes to apply.
      Set to "false" to disable the comment - the plan will still appear in the workflow log.
    default: "true"
    required: false

runs:
  using: "composite"
  steps:
    - name: Terraform Format
      uses: dflook/terraform-fmt-check@9007bad8182158c813d05ea0b2a5735d9579f9ac
      with:
        path: ${{ inputs.path }}

    - name: Terraform Plan
      uses: dflook/terraform-plan@7196a67f47a16ef4f7e12ff0b55205e5eb2cee55
      with:
        path: ${{ inputs.path }}
        label: ${{ inputs.label }}
        backend_config_file: ${{ inputs.backend_config_file }}
        var_file: ${{ inputs.var_file }}
        add_github_comment: ${{ inputs.add_github_comment }}
