name: Lint

on: pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: |
          npm install -g prettier
          prettier --check action.yaml
